### ISSUE TITLE
Vercel build json

### ISSUE THREAD

**Issue by ys-pro-duction** [pawan-suthar1537/instagramclone#1]
{
  "version": 1,
  "builds": [
    {
      "src": "index.js",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "index.js"
    }
  ]
}

**Comment by ys-pro-duction** [comment]
modify it according to your backend folder

**Comment by pawan-suthar1537** [comment]
why

**Comment by pawan-suthar1537** [comment]
who r u
